# Generated by Django 4.2.5 on 2023-10-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_category_slug_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
