# Generated by Django 4.2.5 on 2023-10-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="stripe_charge_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
