# Generated by Django 4.2.5 on 2023-10-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
